# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x05order\"\xa3\x01\n\x0cOrderRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x10\n\x08quantity\x18\x04 \x01(\x01\x12\x0c\n\x04side\x18\x05 \x01(\t\x12\x11\n\tordertype\x18\x06 \x01(\t\x12\x0b\n\x03ltp\x18\x07 \x01(\x01\x12\x11\n\tstopprice\x18\x08 \x01(\x01\x12\x10\n\x08leverage\x18\t \x01(\x01\"0\n\rOrderResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"B\n\rCancelRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x0e\n\x06symbol\x18\x03 \x01(\t\"1\n\x0e\x43\x61ncelResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"k\n\rModifyRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x0e\n\x06symbol\x18\x03 \x01(\t\x12\x11\n\tnew_price\x18\x04 \x01(\x01\x12\x14\n\x0cnew_quantity\x18\x05 \x01(\x01\"1\n\x0eModifyResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\xfc\x01\n\x0cOrderService\x12\x38\n\x0bSubmitOrder\x12\x13.order.OrderRequest\x1a\x14.order.OrderResponse\x12:\n\x0b\x43heckHealth\x12\x14.order.HealthRequest\x1a\x15.order.HealthResponse\x12:\n\x0b\x43\x61ncelOrder\x12\x14.order.CancelRequest\x1a\x15.order.CancelResponse\x12:\n\x0bModifyOrder\x12\x14.order.ModifyRequest\x1a\x15.order.ModifyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERREQUEST']._serialized_start=23
  _globals['_ORDERREQUEST']._serialized_end=186
  _globals['_ORDERRESPONSE']._serialized_start=188
  _globals['_ORDERRESPONSE']._serialized_end=236
  _globals['_HEALTHREQUEST']._serialized_start=238
  _globals['_HEALTHREQUEST']._serialized_end=253
  _globals['_HEALTHRESPONSE']._serialized_start=255
  _globals['_HEALTHRESPONSE']._serialized_end=287
  _globals['_CANCELREQUEST']._serialized_start=289
  _globals['_CANCELREQUEST']._serialized_end=355
  _globals['_CANCELRESPONSE']._serialized_start=357
  _globals['_CANCELRESPONSE']._serialized_end=406
  _globals['_MODIFYREQUEST']._serialized_start=408
  _globals['_MODIFYREQUEST']._serialized_end=515
  _globals['_MODIFYRESPONSE']._serialized_start=517
  _globals['_MODIFYRESPONSE']._serialized_end=566
  _globals['_ORDERSERVICE']._serialized_start=569
  _globals['_ORDERSERVICE']._serialized_end=821
# @@protoc_insertion_point(module_scope)
