// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pnl.proto
// Protobuf C++ Version: 5.29.3

#include "pnl.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace pnl {

inline constexpr WalletResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR WalletResponse::WalletResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct WalletResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WalletResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WalletResponseDefaultTypeInternal() {}
  union {
    WalletResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WalletResponseDefaultTypeInternal _WalletResponse_default_instance_;

inline constexpr WalletRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : user_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        delta_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR WalletRequest::WalletRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct WalletRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WalletRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WalletRequestDefaultTypeInternal() {}
  union {
    WalletRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WalletRequestDefaultTypeInternal _WalletRequest_default_instance_;

inline constexpr TradeUpdate::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : user_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        symbol_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        side_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        price_{0},
        quantity_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TradeUpdate::TradeUpdate(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TradeUpdateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TradeUpdateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TradeUpdateDefaultTypeInternal() {}
  union {
    TradeUpdate _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TradeUpdateDefaultTypeInternal _TradeUpdate_default_instance_;

inline constexpr PnLResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : user_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        equity_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PnLResponse::PnLResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PnLResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PnLResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PnLResponseDefaultTypeInternal() {}
  union {
    PnLResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PnLResponseDefaultTypeInternal _PnLResponse_default_instance_;

inline constexpr PnLRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : user_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PnLRequest::PnLRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PnLRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PnLRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PnLRequestDefaultTypeInternal() {}
  union {
    PnLRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PnLRequestDefaultTypeInternal _PnLRequest_default_instance_;

inline constexpr LiquidationResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : user_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        should_liquidate_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LiquidationResponse::LiquidationResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct LiquidationResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LiquidationResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LiquidationResponseDefaultTypeInternal() {}
  union {
    LiquidationResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LiquidationResponseDefaultTypeInternal _LiquidationResponse_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR Empty::Empty(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct EmptyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmptyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmptyDefaultTypeInternal() {}
  union {
    Empty _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmptyDefaultTypeInternal _Empty_default_instance_;

inline constexpr AllPnLResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : user_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        unrealized_{0},
        realized_{0},
        equity_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AllPnLResponse::AllPnLResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct AllPnLResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AllPnLResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AllPnLResponseDefaultTypeInternal() {}
  union {
    AllPnLResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AllPnLResponseDefaultTypeInternal _AllPnLResponse_default_instance_;
}  // namespace pnl
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_pnl_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_pnl_2eproto = nullptr;
const ::uint32_t
    TableStruct_pnl_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::pnl::PnLRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::pnl::PnLRequest, _impl_.user_id_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::pnl::PnLResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::pnl::PnLResponse, _impl_.user_id_),
        PROTOBUF_FIELD_OFFSET(::pnl::PnLResponse, _impl_.equity_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::pnl::LiquidationResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::pnl::LiquidationResponse, _impl_.user_id_),
        PROTOBUF_FIELD_OFFSET(::pnl::LiquidationResponse, _impl_.should_liquidate_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::pnl::AllPnLResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::pnl::AllPnLResponse, _impl_.user_id_),
        PROTOBUF_FIELD_OFFSET(::pnl::AllPnLResponse, _impl_.unrealized_),
        PROTOBUF_FIELD_OFFSET(::pnl::AllPnLResponse, _impl_.realized_),
        PROTOBUF_FIELD_OFFSET(::pnl::AllPnLResponse, _impl_.equity_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::pnl::WalletRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::pnl::WalletRequest, _impl_.user_id_),
        PROTOBUF_FIELD_OFFSET(::pnl::WalletRequest, _impl_.delta_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::pnl::WalletResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::pnl::WalletResponse, _impl_.success_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::pnl::TradeUpdate, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::pnl::TradeUpdate, _impl_.user_id_),
        PROTOBUF_FIELD_OFFSET(::pnl::TradeUpdate, _impl_.symbol_),
        PROTOBUF_FIELD_OFFSET(::pnl::TradeUpdate, _impl_.price_),
        PROTOBUF_FIELD_OFFSET(::pnl::TradeUpdate, _impl_.quantity_),
        PROTOBUF_FIELD_OFFSET(::pnl::TradeUpdate, _impl_.side_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::pnl::Empty, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::pnl::PnLRequest)},
        {9, -1, -1, sizeof(::pnl::PnLResponse)},
        {19, -1, -1, sizeof(::pnl::LiquidationResponse)},
        {29, -1, -1, sizeof(::pnl::AllPnLResponse)},
        {41, -1, -1, sizeof(::pnl::WalletRequest)},
        {51, -1, -1, sizeof(::pnl::WalletResponse)},
        {60, -1, -1, sizeof(::pnl::TradeUpdate)},
        {73, -1, -1, sizeof(::pnl::Empty)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::pnl::_PnLRequest_default_instance_._instance,
    &::pnl::_PnLResponse_default_instance_._instance,
    &::pnl::_LiquidationResponse_default_instance_._instance,
    &::pnl::_AllPnLResponse_default_instance_._instance,
    &::pnl::_WalletRequest_default_instance_._instance,
    &::pnl::_WalletResponse_default_instance_._instance,
    &::pnl::_TradeUpdate_default_instance_._instance,
    &::pnl::_Empty_default_instance_._instance,
};
const char descriptor_table_protodef_pnl_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\tpnl.proto\022\003pnl\"\035\n\nPnLRequest\022\017\n\007user_i"
    "d\030\001 \001(\t\".\n\013PnLResponse\022\017\n\007user_id\030\001 \001(\t\022"
    "\016\n\006equity\030\002 \001(\001\"@\n\023LiquidationResponse\022\017"
    "\n\007user_id\030\001 \001(\t\022\030\n\020should_liquidate\030\002 \001("
    "\010\"W\n\016AllPnLResponse\022\017\n\007user_id\030\001 \001(\t\022\022\n\n"
    "unrealized\030\002 \001(\001\022\020\n\010realized\030\003 \001(\001\022\016\n\006eq"
    "uity\030\004 \001(\001\"/\n\rWalletRequest\022\017\n\007user_id\030\001"
    " \001(\t\022\r\n\005delta\030\002 \001(\001\"!\n\016WalletResponse\022\017\n"
    "\007success\030\001 \001(\010\"]\n\013TradeUpdate\022\017\n\007user_id"
    "\030\001 \001(\t\022\016\n\006symbol\030\002 \001(\t\022\r\n\005price\030\003 \001(\001\022\020\n"
    "\010quantity\030\004 \001(\001\022\014\n\004side\030\005 \001(\t\"\007\n\005Empty2\222"
    "\002\n\nPnLService\022.\n\tGetEquity\022\017.pnl.PnLRequ"
    "est\032\020.pnl.PnLResponse\022=\n\020CheckLiquidatio"
    "n\022\017.pnl.PnLRequest\032\030.pnl.LiquidationResp"
    "onse\0221\n\tGetAllPnL\022\017.pnl.PnLRequest\032\023.pnl"
    ".AllPnLResponse\0227\n\014UpdateWallet\022\022.pnl.Wa"
    "lletRequest\032\023.pnl.WalletResponse\022)\n\tSend"
    "Trade\022\020.pnl.TradeUpdate\032\n.pnl.Emptyb\006pro"
    "to3"
};
static ::absl::once_flag descriptor_table_pnl_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_pnl_2eproto = {
    false,
    false,
    723,
    descriptor_table_protodef_pnl_2eproto,
    "pnl.proto",
    &descriptor_table_pnl_2eproto_once,
    nullptr,
    0,
    8,
    schemas,
    file_default_instances,
    TableStruct_pnl_2eproto::offsets,
    file_level_enum_descriptors_pnl_2eproto,
    file_level_service_descriptors_pnl_2eproto,
};
namespace pnl {
// ===================================================================

class PnLRequest::_Internal {
 public:
};

PnLRequest::PnLRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:pnl.PnLRequest)
}
inline PROTOBUF_NDEBUG_INLINE PnLRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::pnl::PnLRequest& from_msg)
      : user_id_(arena, from.user_id_),
        _cached_size_{0} {}

PnLRequest::PnLRequest(
    ::google::protobuf::Arena* arena,
    const PnLRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PnLRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:pnl.PnLRequest)
}
inline PROTOBUF_NDEBUG_INLINE PnLRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : user_id_(arena),
        _cached_size_{0} {}

inline void PnLRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PnLRequest::~PnLRequest() {
  // @@protoc_insertion_point(destructor:pnl.PnLRequest)
  SharedDtor(*this);
}
inline void PnLRequest::SharedDtor(MessageLite& self) {
  PnLRequest& this_ = static_cast<PnLRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.user_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PnLRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) PnLRequest(arena);
}
constexpr auto PnLRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PnLRequest),
                                            alignof(PnLRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull PnLRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_PnLRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &PnLRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<PnLRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &PnLRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<PnLRequest>(), &PnLRequest::ByteSizeLong,
            &PnLRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(PnLRequest, _impl_._cached_size_),
        false,
    },
    &PnLRequest::kDescriptorMethods,
    &descriptor_table_pnl_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* PnLRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 30, 2> PnLRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::pnl::PnLRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string user_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(PnLRequest, _impl_.user_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string user_id = 1;
    {PROTOBUF_FIELD_OFFSET(PnLRequest, _impl_.user_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\16\7\0\0\0\0\0\0"
    "pnl.PnLRequest"
    "user_id"
  }},
};

PROTOBUF_NOINLINE void PnLRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:pnl.PnLRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.user_id_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* PnLRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const PnLRequest& this_ = static_cast<const PnLRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* PnLRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const PnLRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:pnl.PnLRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string user_id = 1;
          if (!this_._internal_user_id().empty()) {
            const std::string& _s = this_._internal_user_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "pnl.PnLRequest.user_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:pnl.PnLRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t PnLRequest::ByteSizeLong(const MessageLite& base) {
          const PnLRequest& this_ = static_cast<const PnLRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t PnLRequest::ByteSizeLong() const {
          const PnLRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:pnl.PnLRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string user_id = 1;
            if (!this_._internal_user_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_user_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void PnLRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PnLRequest*>(&to_msg);
  auto& from = static_cast<const PnLRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:pnl.PnLRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_user_id().empty()) {
    _this->_internal_set_user_id(from._internal_user_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PnLRequest::CopyFrom(const PnLRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pnl.PnLRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PnLRequest::InternalSwap(PnLRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.user_id_, &other->_impl_.user_id_, arena);
}

::google::protobuf::Metadata PnLRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PnLResponse::_Internal {
 public:
};

PnLResponse::PnLResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:pnl.PnLResponse)
}
inline PROTOBUF_NDEBUG_INLINE PnLResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::pnl::PnLResponse& from_msg)
      : user_id_(arena, from.user_id_),
        _cached_size_{0} {}

PnLResponse::PnLResponse(
    ::google::protobuf::Arena* arena,
    const PnLResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PnLResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.equity_ = from._impl_.equity_;

  // @@protoc_insertion_point(copy_constructor:pnl.PnLResponse)
}
inline PROTOBUF_NDEBUG_INLINE PnLResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : user_id_(arena),
        _cached_size_{0} {}

inline void PnLResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.equity_ = {};
}
PnLResponse::~PnLResponse() {
  // @@protoc_insertion_point(destructor:pnl.PnLResponse)
  SharedDtor(*this);
}
inline void PnLResponse::SharedDtor(MessageLite& self) {
  PnLResponse& this_ = static_cast<PnLResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.user_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PnLResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) PnLResponse(arena);
}
constexpr auto PnLResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PnLResponse),
                                            alignof(PnLResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull PnLResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_PnLResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &PnLResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<PnLResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &PnLResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<PnLResponse>(), &PnLResponse::ByteSizeLong,
            &PnLResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(PnLResponse, _impl_._cached_size_),
        false,
    },
    &PnLResponse::kDescriptorMethods,
    &descriptor_table_pnl_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* PnLResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 31, 2> PnLResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::pnl::PnLResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // double equity = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(PnLResponse, _impl_.equity_)}},
    // string user_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(PnLResponse, _impl_.user_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string user_id = 1;
    {PROTOBUF_FIELD_OFFSET(PnLResponse, _impl_.user_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // double equity = 2;
    {PROTOBUF_FIELD_OFFSET(PnLResponse, _impl_.equity_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
    "\17\7\0\0\0\0\0\0"
    "pnl.PnLResponse"
    "user_id"
  }},
};

PROTOBUF_NOINLINE void PnLResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:pnl.PnLResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.user_id_.ClearToEmpty();
  _impl_.equity_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* PnLResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const PnLResponse& this_ = static_cast<const PnLResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* PnLResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const PnLResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:pnl.PnLResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string user_id = 1;
          if (!this_._internal_user_id().empty()) {
            const std::string& _s = this_._internal_user_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "pnl.PnLResponse.user_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // double equity = 2;
          if (::absl::bit_cast<::uint64_t>(this_._internal_equity()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                2, this_._internal_equity(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:pnl.PnLResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t PnLResponse::ByteSizeLong(const MessageLite& base) {
          const PnLResponse& this_ = static_cast<const PnLResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t PnLResponse::ByteSizeLong() const {
          const PnLResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:pnl.PnLResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string user_id = 1;
            if (!this_._internal_user_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_user_id());
            }
            // double equity = 2;
            if (::absl::bit_cast<::uint64_t>(this_._internal_equity()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void PnLResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PnLResponse*>(&to_msg);
  auto& from = static_cast<const PnLResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:pnl.PnLResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_user_id().empty()) {
    _this->_internal_set_user_id(from._internal_user_id());
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_equity()) != 0) {
    _this->_impl_.equity_ = from._impl_.equity_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PnLResponse::CopyFrom(const PnLResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pnl.PnLResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PnLResponse::InternalSwap(PnLResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.user_id_, &other->_impl_.user_id_, arena);
        swap(_impl_.equity_, other->_impl_.equity_);
}

::google::protobuf::Metadata PnLResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class LiquidationResponse::_Internal {
 public:
};

LiquidationResponse::LiquidationResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:pnl.LiquidationResponse)
}
inline PROTOBUF_NDEBUG_INLINE LiquidationResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::pnl::LiquidationResponse& from_msg)
      : user_id_(arena, from.user_id_),
        _cached_size_{0} {}

LiquidationResponse::LiquidationResponse(
    ::google::protobuf::Arena* arena,
    const LiquidationResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  LiquidationResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.should_liquidate_ = from._impl_.should_liquidate_;

  // @@protoc_insertion_point(copy_constructor:pnl.LiquidationResponse)
}
inline PROTOBUF_NDEBUG_INLINE LiquidationResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : user_id_(arena),
        _cached_size_{0} {}

inline void LiquidationResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.should_liquidate_ = {};
}
LiquidationResponse::~LiquidationResponse() {
  // @@protoc_insertion_point(destructor:pnl.LiquidationResponse)
  SharedDtor(*this);
}
inline void LiquidationResponse::SharedDtor(MessageLite& self) {
  LiquidationResponse& this_ = static_cast<LiquidationResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.user_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* LiquidationResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) LiquidationResponse(arena);
}
constexpr auto LiquidationResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(LiquidationResponse),
                                            alignof(LiquidationResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull LiquidationResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_LiquidationResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &LiquidationResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<LiquidationResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &LiquidationResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<LiquidationResponse>(), &LiquidationResponse::ByteSizeLong,
            &LiquidationResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(LiquidationResponse, _impl_._cached_size_),
        false,
    },
    &LiquidationResponse::kDescriptorMethods,
    &descriptor_table_pnl_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* LiquidationResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 39, 2> LiquidationResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::pnl::LiquidationResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool should_liquidate = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(LiquidationResponse, _impl_.should_liquidate_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(LiquidationResponse, _impl_.should_liquidate_)}},
    // string user_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(LiquidationResponse, _impl_.user_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string user_id = 1;
    {PROTOBUF_FIELD_OFFSET(LiquidationResponse, _impl_.user_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool should_liquidate = 2;
    {PROTOBUF_FIELD_OFFSET(LiquidationResponse, _impl_.should_liquidate_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\27\7\0\0\0\0\0\0"
    "pnl.LiquidationResponse"
    "user_id"
  }},
};

PROTOBUF_NOINLINE void LiquidationResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:pnl.LiquidationResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.user_id_.ClearToEmpty();
  _impl_.should_liquidate_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* LiquidationResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const LiquidationResponse& this_ = static_cast<const LiquidationResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* LiquidationResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const LiquidationResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:pnl.LiquidationResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string user_id = 1;
          if (!this_._internal_user_id().empty()) {
            const std::string& _s = this_._internal_user_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "pnl.LiquidationResponse.user_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // bool should_liquidate = 2;
          if (this_._internal_should_liquidate() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_should_liquidate(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:pnl.LiquidationResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t LiquidationResponse::ByteSizeLong(const MessageLite& base) {
          const LiquidationResponse& this_ = static_cast<const LiquidationResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t LiquidationResponse::ByteSizeLong() const {
          const LiquidationResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:pnl.LiquidationResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string user_id = 1;
            if (!this_._internal_user_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_user_id());
            }
            // bool should_liquidate = 2;
            if (this_._internal_should_liquidate() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void LiquidationResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<LiquidationResponse*>(&to_msg);
  auto& from = static_cast<const LiquidationResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:pnl.LiquidationResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_user_id().empty()) {
    _this->_internal_set_user_id(from._internal_user_id());
  }
  if (from._internal_should_liquidate() != 0) {
    _this->_impl_.should_liquidate_ = from._impl_.should_liquidate_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LiquidationResponse::CopyFrom(const LiquidationResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pnl.LiquidationResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void LiquidationResponse::InternalSwap(LiquidationResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.user_id_, &other->_impl_.user_id_, arena);
        swap(_impl_.should_liquidate_, other->_impl_.should_liquidate_);
}

::google::protobuf::Metadata LiquidationResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AllPnLResponse::_Internal {
 public:
};

AllPnLResponse::AllPnLResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:pnl.AllPnLResponse)
}
inline PROTOBUF_NDEBUG_INLINE AllPnLResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::pnl::AllPnLResponse& from_msg)
      : user_id_(arena, from.user_id_),
        _cached_size_{0} {}

AllPnLResponse::AllPnLResponse(
    ::google::protobuf::Arena* arena,
    const AllPnLResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AllPnLResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, unrealized_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, unrealized_),
           offsetof(Impl_, equity_) -
               offsetof(Impl_, unrealized_) +
               sizeof(Impl_::equity_));

  // @@protoc_insertion_point(copy_constructor:pnl.AllPnLResponse)
}
inline PROTOBUF_NDEBUG_INLINE AllPnLResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : user_id_(arena),
        _cached_size_{0} {}

inline void AllPnLResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, unrealized_),
           0,
           offsetof(Impl_, equity_) -
               offsetof(Impl_, unrealized_) +
               sizeof(Impl_::equity_));
}
AllPnLResponse::~AllPnLResponse() {
  // @@protoc_insertion_point(destructor:pnl.AllPnLResponse)
  SharedDtor(*this);
}
inline void AllPnLResponse::SharedDtor(MessageLite& self) {
  AllPnLResponse& this_ = static_cast<AllPnLResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.user_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* AllPnLResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) AllPnLResponse(arena);
}
constexpr auto AllPnLResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(AllPnLResponse),
                                            alignof(AllPnLResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull AllPnLResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_AllPnLResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &AllPnLResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<AllPnLResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &AllPnLResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<AllPnLResponse>(), &AllPnLResponse::ByteSizeLong,
            &AllPnLResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(AllPnLResponse, _impl_._cached_size_),
        false,
    },
    &AllPnLResponse::kDescriptorMethods,
    &descriptor_table_pnl_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* AllPnLResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 34, 2> AllPnLResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::pnl::AllPnLResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // double equity = 4;
    {::_pbi::TcParser::FastF64S1,
     {33, 63, 0, PROTOBUF_FIELD_OFFSET(AllPnLResponse, _impl_.equity_)}},
    // string user_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(AllPnLResponse, _impl_.user_id_)}},
    // double unrealized = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(AllPnLResponse, _impl_.unrealized_)}},
    // double realized = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 63, 0, PROTOBUF_FIELD_OFFSET(AllPnLResponse, _impl_.realized_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string user_id = 1;
    {PROTOBUF_FIELD_OFFSET(AllPnLResponse, _impl_.user_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // double unrealized = 2;
    {PROTOBUF_FIELD_OFFSET(AllPnLResponse, _impl_.unrealized_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double realized = 3;
    {PROTOBUF_FIELD_OFFSET(AllPnLResponse, _impl_.realized_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double equity = 4;
    {PROTOBUF_FIELD_OFFSET(AllPnLResponse, _impl_.equity_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
    "\22\7\0\0\0\0\0\0"
    "pnl.AllPnLResponse"
    "user_id"
  }},
};

PROTOBUF_NOINLINE void AllPnLResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:pnl.AllPnLResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.user_id_.ClearToEmpty();
  ::memset(&_impl_.unrealized_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.equity_) -
      reinterpret_cast<char*>(&_impl_.unrealized_)) + sizeof(_impl_.equity_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* AllPnLResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const AllPnLResponse& this_ = static_cast<const AllPnLResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* AllPnLResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const AllPnLResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:pnl.AllPnLResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string user_id = 1;
          if (!this_._internal_user_id().empty()) {
            const std::string& _s = this_._internal_user_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "pnl.AllPnLResponse.user_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // double unrealized = 2;
          if (::absl::bit_cast<::uint64_t>(this_._internal_unrealized()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                2, this_._internal_unrealized(), target);
          }

          // double realized = 3;
          if (::absl::bit_cast<::uint64_t>(this_._internal_realized()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                3, this_._internal_realized(), target);
          }

          // double equity = 4;
          if (::absl::bit_cast<::uint64_t>(this_._internal_equity()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                4, this_._internal_equity(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:pnl.AllPnLResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t AllPnLResponse::ByteSizeLong(const MessageLite& base) {
          const AllPnLResponse& this_ = static_cast<const AllPnLResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t AllPnLResponse::ByteSizeLong() const {
          const AllPnLResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:pnl.AllPnLResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string user_id = 1;
            if (!this_._internal_user_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_user_id());
            }
            // double unrealized = 2;
            if (::absl::bit_cast<::uint64_t>(this_._internal_unrealized()) != 0) {
              total_size += 9;
            }
            // double realized = 3;
            if (::absl::bit_cast<::uint64_t>(this_._internal_realized()) != 0) {
              total_size += 9;
            }
            // double equity = 4;
            if (::absl::bit_cast<::uint64_t>(this_._internal_equity()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void AllPnLResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AllPnLResponse*>(&to_msg);
  auto& from = static_cast<const AllPnLResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:pnl.AllPnLResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_user_id().empty()) {
    _this->_internal_set_user_id(from._internal_user_id());
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_unrealized()) != 0) {
    _this->_impl_.unrealized_ = from._impl_.unrealized_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_realized()) != 0) {
    _this->_impl_.realized_ = from._impl_.realized_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_equity()) != 0) {
    _this->_impl_.equity_ = from._impl_.equity_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AllPnLResponse::CopyFrom(const AllPnLResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pnl.AllPnLResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AllPnLResponse::InternalSwap(AllPnLResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.user_id_, &other->_impl_.user_id_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AllPnLResponse, _impl_.equity_)
      + sizeof(AllPnLResponse::_impl_.equity_)
      - PROTOBUF_FIELD_OFFSET(AllPnLResponse, _impl_.unrealized_)>(
          reinterpret_cast<char*>(&_impl_.unrealized_),
          reinterpret_cast<char*>(&other->_impl_.unrealized_));
}

::google::protobuf::Metadata AllPnLResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class WalletRequest::_Internal {
 public:
};

WalletRequest::WalletRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:pnl.WalletRequest)
}
inline PROTOBUF_NDEBUG_INLINE WalletRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::pnl::WalletRequest& from_msg)
      : user_id_(arena, from.user_id_),
        _cached_size_{0} {}

WalletRequest::WalletRequest(
    ::google::protobuf::Arena* arena,
    const WalletRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  WalletRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.delta_ = from._impl_.delta_;

  // @@protoc_insertion_point(copy_constructor:pnl.WalletRequest)
}
inline PROTOBUF_NDEBUG_INLINE WalletRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : user_id_(arena),
        _cached_size_{0} {}

inline void WalletRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.delta_ = {};
}
WalletRequest::~WalletRequest() {
  // @@protoc_insertion_point(destructor:pnl.WalletRequest)
  SharedDtor(*this);
}
inline void WalletRequest::SharedDtor(MessageLite& self) {
  WalletRequest& this_ = static_cast<WalletRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.user_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* WalletRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) WalletRequest(arena);
}
constexpr auto WalletRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(WalletRequest),
                                            alignof(WalletRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull WalletRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_WalletRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &WalletRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<WalletRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &WalletRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<WalletRequest>(), &WalletRequest::ByteSizeLong,
            &WalletRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(WalletRequest, _impl_._cached_size_),
        false,
    },
    &WalletRequest::kDescriptorMethods,
    &descriptor_table_pnl_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* WalletRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 33, 2> WalletRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::pnl::WalletRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // double delta = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(WalletRequest, _impl_.delta_)}},
    // string user_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(WalletRequest, _impl_.user_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string user_id = 1;
    {PROTOBUF_FIELD_OFFSET(WalletRequest, _impl_.user_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // double delta = 2;
    {PROTOBUF_FIELD_OFFSET(WalletRequest, _impl_.delta_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
    "\21\7\0\0\0\0\0\0"
    "pnl.WalletRequest"
    "user_id"
  }},
};

PROTOBUF_NOINLINE void WalletRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:pnl.WalletRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.user_id_.ClearToEmpty();
  _impl_.delta_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* WalletRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const WalletRequest& this_ = static_cast<const WalletRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* WalletRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const WalletRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:pnl.WalletRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string user_id = 1;
          if (!this_._internal_user_id().empty()) {
            const std::string& _s = this_._internal_user_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "pnl.WalletRequest.user_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // double delta = 2;
          if (::absl::bit_cast<::uint64_t>(this_._internal_delta()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                2, this_._internal_delta(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:pnl.WalletRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t WalletRequest::ByteSizeLong(const MessageLite& base) {
          const WalletRequest& this_ = static_cast<const WalletRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t WalletRequest::ByteSizeLong() const {
          const WalletRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:pnl.WalletRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string user_id = 1;
            if (!this_._internal_user_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_user_id());
            }
            // double delta = 2;
            if (::absl::bit_cast<::uint64_t>(this_._internal_delta()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void WalletRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<WalletRequest*>(&to_msg);
  auto& from = static_cast<const WalletRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:pnl.WalletRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_user_id().empty()) {
    _this->_internal_set_user_id(from._internal_user_id());
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_delta()) != 0) {
    _this->_impl_.delta_ = from._impl_.delta_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void WalletRequest::CopyFrom(const WalletRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pnl.WalletRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void WalletRequest::InternalSwap(WalletRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.user_id_, &other->_impl_.user_id_, arena);
        swap(_impl_.delta_, other->_impl_.delta_);
}

::google::protobuf::Metadata WalletRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class WalletResponse::_Internal {
 public:
};

WalletResponse::WalletResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:pnl.WalletResponse)
}
WalletResponse::WalletResponse(
    ::google::protobuf::Arena* arena, const WalletResponse& from)
    : WalletResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE WalletResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void WalletResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.success_ = {};
}
WalletResponse::~WalletResponse() {
  // @@protoc_insertion_point(destructor:pnl.WalletResponse)
  SharedDtor(*this);
}
inline void WalletResponse::SharedDtor(MessageLite& self) {
  WalletResponse& this_ = static_cast<WalletResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* WalletResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) WalletResponse(arena);
}
constexpr auto WalletResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(WalletResponse),
                                            alignof(WalletResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull WalletResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_WalletResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &WalletResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<WalletResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &WalletResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<WalletResponse>(), &WalletResponse::ByteSizeLong,
            &WalletResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(WalletResponse, _impl_._cached_size_),
        false,
    },
    &WalletResponse::kDescriptorMethods,
    &descriptor_table_pnl_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* WalletResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> WalletResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::pnl::WalletResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool success = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(WalletResponse, _impl_.success_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(WalletResponse, _impl_.success_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool success = 1;
    {PROTOBUF_FIELD_OFFSET(WalletResponse, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void WalletResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:pnl.WalletResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.success_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* WalletResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const WalletResponse& this_ = static_cast<const WalletResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* WalletResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const WalletResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:pnl.WalletResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool success = 1;
          if (this_._internal_success() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_success(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:pnl.WalletResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t WalletResponse::ByteSizeLong(const MessageLite& base) {
          const WalletResponse& this_ = static_cast<const WalletResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t WalletResponse::ByteSizeLong() const {
          const WalletResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:pnl.WalletResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // bool success = 1;
            if (this_._internal_success() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void WalletResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<WalletResponse*>(&to_msg);
  auto& from = static_cast<const WalletResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:pnl.WalletResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_success() != 0) {
    _this->_impl_.success_ = from._impl_.success_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void WalletResponse::CopyFrom(const WalletResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pnl.WalletResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void WalletResponse::InternalSwap(WalletResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.success_, other->_impl_.success_);
}

::google::protobuf::Metadata WalletResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class TradeUpdate::_Internal {
 public:
};

TradeUpdate::TradeUpdate(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:pnl.TradeUpdate)
}
inline PROTOBUF_NDEBUG_INLINE TradeUpdate::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::pnl::TradeUpdate& from_msg)
      : user_id_(arena, from.user_id_),
        symbol_(arena, from.symbol_),
        side_(arena, from.side_),
        _cached_size_{0} {}

TradeUpdate::TradeUpdate(
    ::google::protobuf::Arena* arena,
    const TradeUpdate& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TradeUpdate* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, price_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, price_),
           offsetof(Impl_, quantity_) -
               offsetof(Impl_, price_) +
               sizeof(Impl_::quantity_));

  // @@protoc_insertion_point(copy_constructor:pnl.TradeUpdate)
}
inline PROTOBUF_NDEBUG_INLINE TradeUpdate::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : user_id_(arena),
        symbol_(arena),
        side_(arena),
        _cached_size_{0} {}

inline void TradeUpdate::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, price_),
           0,
           offsetof(Impl_, quantity_) -
               offsetof(Impl_, price_) +
               sizeof(Impl_::quantity_));
}
TradeUpdate::~TradeUpdate() {
  // @@protoc_insertion_point(destructor:pnl.TradeUpdate)
  SharedDtor(*this);
}
inline void TradeUpdate::SharedDtor(MessageLite& self) {
  TradeUpdate& this_ = static_cast<TradeUpdate&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.user_id_.Destroy();
  this_._impl_.symbol_.Destroy();
  this_._impl_.side_.Destroy();
  this_._impl_.~Impl_();
}

inline void* TradeUpdate::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) TradeUpdate(arena);
}
constexpr auto TradeUpdate::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(TradeUpdate),
                                            alignof(TradeUpdate));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull TradeUpdate::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_TradeUpdate_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &TradeUpdate::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<TradeUpdate>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &TradeUpdate::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<TradeUpdate>(), &TradeUpdate::ByteSizeLong,
            &TradeUpdate::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(TradeUpdate, _impl_._cached_size_),
        false,
    },
    &TradeUpdate::kDescriptorMethods,
    &descriptor_table_pnl_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* TradeUpdate::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 41, 2> TradeUpdate::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::pnl::TradeUpdate>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string user_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(TradeUpdate, _impl_.user_id_)}},
    // string symbol = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(TradeUpdate, _impl_.symbol_)}},
    // double price = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 63, 0, PROTOBUF_FIELD_OFFSET(TradeUpdate, _impl_.price_)}},
    // double quantity = 4;
    {::_pbi::TcParser::FastF64S1,
     {33, 63, 0, PROTOBUF_FIELD_OFFSET(TradeUpdate, _impl_.quantity_)}},
    // string side = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(TradeUpdate, _impl_.side_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string user_id = 1;
    {PROTOBUF_FIELD_OFFSET(TradeUpdate, _impl_.user_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string symbol = 2;
    {PROTOBUF_FIELD_OFFSET(TradeUpdate, _impl_.symbol_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // double price = 3;
    {PROTOBUF_FIELD_OFFSET(TradeUpdate, _impl_.price_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double quantity = 4;
    {PROTOBUF_FIELD_OFFSET(TradeUpdate, _impl_.quantity_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // string side = 5;
    {PROTOBUF_FIELD_OFFSET(TradeUpdate, _impl_.side_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\17\7\6\0\0\4\0\0"
    "pnl.TradeUpdate"
    "user_id"
    "symbol"
    "side"
  }},
};

PROTOBUF_NOINLINE void TradeUpdate::Clear() {
// @@protoc_insertion_point(message_clear_start:pnl.TradeUpdate)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.user_id_.ClearToEmpty();
  _impl_.symbol_.ClearToEmpty();
  _impl_.side_.ClearToEmpty();
  ::memset(&_impl_.price_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.quantity_) -
      reinterpret_cast<char*>(&_impl_.price_)) + sizeof(_impl_.quantity_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* TradeUpdate::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const TradeUpdate& this_ = static_cast<const TradeUpdate&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* TradeUpdate::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const TradeUpdate& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:pnl.TradeUpdate)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string user_id = 1;
          if (!this_._internal_user_id().empty()) {
            const std::string& _s = this_._internal_user_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "pnl.TradeUpdate.user_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string symbol = 2;
          if (!this_._internal_symbol().empty()) {
            const std::string& _s = this_._internal_symbol();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "pnl.TradeUpdate.symbol");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // double price = 3;
          if (::absl::bit_cast<::uint64_t>(this_._internal_price()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                3, this_._internal_price(), target);
          }

          // double quantity = 4;
          if (::absl::bit_cast<::uint64_t>(this_._internal_quantity()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                4, this_._internal_quantity(), target);
          }

          // string side = 5;
          if (!this_._internal_side().empty()) {
            const std::string& _s = this_._internal_side();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "pnl.TradeUpdate.side");
            target = stream->WriteStringMaybeAliased(5, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:pnl.TradeUpdate)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t TradeUpdate::ByteSizeLong(const MessageLite& base) {
          const TradeUpdate& this_ = static_cast<const TradeUpdate&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t TradeUpdate::ByteSizeLong() const {
          const TradeUpdate& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:pnl.TradeUpdate)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string user_id = 1;
            if (!this_._internal_user_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_user_id());
            }
            // string symbol = 2;
            if (!this_._internal_symbol().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_symbol());
            }
            // string side = 5;
            if (!this_._internal_side().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_side());
            }
            // double price = 3;
            if (::absl::bit_cast<::uint64_t>(this_._internal_price()) != 0) {
              total_size += 9;
            }
            // double quantity = 4;
            if (::absl::bit_cast<::uint64_t>(this_._internal_quantity()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void TradeUpdate::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TradeUpdate*>(&to_msg);
  auto& from = static_cast<const TradeUpdate&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:pnl.TradeUpdate)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_user_id().empty()) {
    _this->_internal_set_user_id(from._internal_user_id());
  }
  if (!from._internal_symbol().empty()) {
    _this->_internal_set_symbol(from._internal_symbol());
  }
  if (!from._internal_side().empty()) {
    _this->_internal_set_side(from._internal_side());
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_price()) != 0) {
    _this->_impl_.price_ = from._impl_.price_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_quantity()) != 0) {
    _this->_impl_.quantity_ = from._impl_.quantity_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TradeUpdate::CopyFrom(const TradeUpdate& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pnl.TradeUpdate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TradeUpdate::InternalSwap(TradeUpdate* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.user_id_, &other->_impl_.user_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.symbol_, &other->_impl_.symbol_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.side_, &other->_impl_.side_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TradeUpdate, _impl_.quantity_)
      + sizeof(TradeUpdate::_impl_.quantity_)
      - PROTOBUF_FIELD_OFFSET(TradeUpdate, _impl_.price_)>(
          reinterpret_cast<char*>(&_impl_.price_),
          reinterpret_cast<char*>(&other->_impl_.price_));
}

::google::protobuf::Metadata TradeUpdate::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Empty::_Internal {
 public:
};

Empty::Empty(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:pnl.Empty)
}
Empty::Empty(
    ::google::protobuf::Arena* arena,
    const Empty& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Empty* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:pnl.Empty)
}

inline void* Empty::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Empty(arena);
}
constexpr auto Empty::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Empty),
                                            alignof(Empty));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Empty::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Empty_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Empty::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<Empty>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Empty::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<Empty>(), &Empty::ByteSizeLong,
            &Empty::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Empty, _impl_._cached_size_),
        false,
    },
    &Empty::kDescriptorMethods,
    &descriptor_table_pnl_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Empty::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> Empty::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::pnl::Empty>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata Empty::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace pnl
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_pnl_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
