// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user.proto
// Protobuf C++ Version: 5.29.3

#include "user.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace user {

inline constexpr WalletUpdateRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : user_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        reason_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        amount_change_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR WalletUpdateRequest::WalletUpdateRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct WalletUpdateRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WalletUpdateRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WalletUpdateRequestDefaultTypeInternal() {}
  union {
    WalletUpdateRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WalletUpdateRequestDefaultTypeInternal _WalletUpdateRequest_default_instance_;

inline constexpr WalletResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : new_balance_{0},
        available_balance_{0},
        used_margin_{0},
        success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR WalletResponse::WalletResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct WalletResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WalletResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WalletResponseDefaultTypeInternal() {}
  union {
    WalletResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WalletResponseDefaultTypeInternal _WalletResponse_default_instance_;

inline constexpr UserMetadataResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : user_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        role_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        kyc_verified_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UserMetadataResponse::UserMetadataResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UserMetadataResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UserMetadataResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UserMetadataResponseDefaultTypeInternal() {}
  union {
    UserMetadataResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UserMetadataResponseDefaultTypeInternal _UserMetadataResponse_default_instance_;

inline constexpr UserIdRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : user_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UserIdRequest::UserIdRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UserIdRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UserIdRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UserIdRequestDefaultTypeInternal() {}
  union {
    UserIdRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UserIdRequestDefaultTypeInternal _UserIdRequest_default_instance_;
}  // namespace user
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_user_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_user_2eproto = nullptr;
const ::uint32_t
    TableStruct_user_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::user::WalletUpdateRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::user::WalletUpdateRequest, _impl_.user_id_),
        PROTOBUF_FIELD_OFFSET(::user::WalletUpdateRequest, _impl_.amount_change_),
        PROTOBUF_FIELD_OFFSET(::user::WalletUpdateRequest, _impl_.reason_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::user::WalletResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::user::WalletResponse, _impl_.new_balance_),
        PROTOBUF_FIELD_OFFSET(::user::WalletResponse, _impl_.success_),
        PROTOBUF_FIELD_OFFSET(::user::WalletResponse, _impl_.available_balance_),
        PROTOBUF_FIELD_OFFSET(::user::WalletResponse, _impl_.used_margin_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::user::UserIdRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::user::UserIdRequest, _impl_.user_id_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::user::UserMetadataResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::user::UserMetadataResponse, _impl_.user_id_),
        PROTOBUF_FIELD_OFFSET(::user::UserMetadataResponse, _impl_.role_),
        PROTOBUF_FIELD_OFFSET(::user::UserMetadataResponse, _impl_.kyc_verified_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::user::WalletUpdateRequest)},
        {11, -1, -1, sizeof(::user::WalletResponse)},
        {23, -1, -1, sizeof(::user::UserIdRequest)},
        {32, -1, -1, sizeof(::user::UserMetadataResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::user::_WalletUpdateRequest_default_instance_._instance,
    &::user::_WalletResponse_default_instance_._instance,
    &::user::_UserIdRequest_default_instance_._instance,
    &::user::_UserMetadataResponse_default_instance_._instance,
};
const char descriptor_table_protodef_user_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\nuser.proto\022\004user\"M\n\023WalletUpdateReques"
    "t\022\017\n\007user_id\030\001 \001(\t\022\025\n\ramount_change\030\002 \001("
    "\001\022\016\n\006reason\030\003 \001(\t\"f\n\016WalletResponse\022\023\n\013n"
    "ew_balance\030\001 \001(\001\022\017\n\007success\030\002 \001(\010\022\031\n\021ava"
    "ilable_balance\030\003 \001(\001\022\023\n\013used_margin\030\004 \001("
    "\001\" \n\rUserIdRequest\022\017\n\007user_id\030\001 \001(\t\"K\n\024U"
    "serMetadataResponse\022\017\n\007user_id\030\001 \001(\t\022\014\n\004"
    "role\030\002 \001(\t\022\024\n\014kyc_verified\030\003 \001(\0102\312\001\n\013Use"
    "rService\022\?\n\014UpdateWallet\022\031.user.WalletUp"
    "dateRequest\032\024.user.WalletResponse\022B\n\017Get"
    "UserMetadata\022\023.user.UserIdRequest\032\032.user"
    ".UserMetadataResponse\0226\n\tGetWallet\022\023.use"
    "r.UserIdRequest\032\024.user.WalletResponseb\006p"
    "roto3"
};
static ::absl::once_flag descriptor_table_user_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_user_2eproto = {
    false,
    false,
    525,
    descriptor_table_protodef_user_2eproto,
    "user.proto",
    &descriptor_table_user_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_user_2eproto::offsets,
    file_level_enum_descriptors_user_2eproto,
    file_level_service_descriptors_user_2eproto,
};
namespace user {
// ===================================================================

class WalletUpdateRequest::_Internal {
 public:
};

WalletUpdateRequest::WalletUpdateRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:user.WalletUpdateRequest)
}
inline PROTOBUF_NDEBUG_INLINE WalletUpdateRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::user::WalletUpdateRequest& from_msg)
      : user_id_(arena, from.user_id_),
        reason_(arena, from.reason_),
        _cached_size_{0} {}

WalletUpdateRequest::WalletUpdateRequest(
    ::google::protobuf::Arena* arena,
    const WalletUpdateRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  WalletUpdateRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.amount_change_ = from._impl_.amount_change_;

  // @@protoc_insertion_point(copy_constructor:user.WalletUpdateRequest)
}
inline PROTOBUF_NDEBUG_INLINE WalletUpdateRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : user_id_(arena),
        reason_(arena),
        _cached_size_{0} {}

inline void WalletUpdateRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.amount_change_ = {};
}
WalletUpdateRequest::~WalletUpdateRequest() {
  // @@protoc_insertion_point(destructor:user.WalletUpdateRequest)
  SharedDtor(*this);
}
inline void WalletUpdateRequest::SharedDtor(MessageLite& self) {
  WalletUpdateRequest& this_ = static_cast<WalletUpdateRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.user_id_.Destroy();
  this_._impl_.reason_.Destroy();
  this_._impl_.~Impl_();
}

inline void* WalletUpdateRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) WalletUpdateRequest(arena);
}
constexpr auto WalletUpdateRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(WalletUpdateRequest),
                                            alignof(WalletUpdateRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull WalletUpdateRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_WalletUpdateRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &WalletUpdateRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<WalletUpdateRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &WalletUpdateRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<WalletUpdateRequest>(), &WalletUpdateRequest::ByteSizeLong,
            &WalletUpdateRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(WalletUpdateRequest, _impl_._cached_size_),
        false,
    },
    &WalletUpdateRequest::kDescriptorMethods,
    &descriptor_table_user_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* WalletUpdateRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 46, 2> WalletUpdateRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::user::WalletUpdateRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string user_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(WalletUpdateRequest, _impl_.user_id_)}},
    // double amount_change = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(WalletUpdateRequest, _impl_.amount_change_)}},
    // string reason = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(WalletUpdateRequest, _impl_.reason_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string user_id = 1;
    {PROTOBUF_FIELD_OFFSET(WalletUpdateRequest, _impl_.user_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // double amount_change = 2;
    {PROTOBUF_FIELD_OFFSET(WalletUpdateRequest, _impl_.amount_change_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // string reason = 3;
    {PROTOBUF_FIELD_OFFSET(WalletUpdateRequest, _impl_.reason_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\30\7\0\6\0\0\0\0"
    "user.WalletUpdateRequest"
    "user_id"
    "reason"
  }},
};

PROTOBUF_NOINLINE void WalletUpdateRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:user.WalletUpdateRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.user_id_.ClearToEmpty();
  _impl_.reason_.ClearToEmpty();
  _impl_.amount_change_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* WalletUpdateRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const WalletUpdateRequest& this_ = static_cast<const WalletUpdateRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* WalletUpdateRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const WalletUpdateRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:user.WalletUpdateRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string user_id = 1;
          if (!this_._internal_user_id().empty()) {
            const std::string& _s = this_._internal_user_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "user.WalletUpdateRequest.user_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // double amount_change = 2;
          if (::absl::bit_cast<::uint64_t>(this_._internal_amount_change()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                2, this_._internal_amount_change(), target);
          }

          // string reason = 3;
          if (!this_._internal_reason().empty()) {
            const std::string& _s = this_._internal_reason();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "user.WalletUpdateRequest.reason");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:user.WalletUpdateRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t WalletUpdateRequest::ByteSizeLong(const MessageLite& base) {
          const WalletUpdateRequest& this_ = static_cast<const WalletUpdateRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t WalletUpdateRequest::ByteSizeLong() const {
          const WalletUpdateRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:user.WalletUpdateRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string user_id = 1;
            if (!this_._internal_user_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_user_id());
            }
            // string reason = 3;
            if (!this_._internal_reason().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_reason());
            }
            // double amount_change = 2;
            if (::absl::bit_cast<::uint64_t>(this_._internal_amount_change()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void WalletUpdateRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<WalletUpdateRequest*>(&to_msg);
  auto& from = static_cast<const WalletUpdateRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:user.WalletUpdateRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_user_id().empty()) {
    _this->_internal_set_user_id(from._internal_user_id());
  }
  if (!from._internal_reason().empty()) {
    _this->_internal_set_reason(from._internal_reason());
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_amount_change()) != 0) {
    _this->_impl_.amount_change_ = from._impl_.amount_change_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void WalletUpdateRequest::CopyFrom(const WalletUpdateRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:user.WalletUpdateRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void WalletUpdateRequest::InternalSwap(WalletUpdateRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.user_id_, &other->_impl_.user_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.reason_, &other->_impl_.reason_, arena);
        swap(_impl_.amount_change_, other->_impl_.amount_change_);
}

::google::protobuf::Metadata WalletUpdateRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class WalletResponse::_Internal {
 public:
};

WalletResponse::WalletResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:user.WalletResponse)
}
WalletResponse::WalletResponse(
    ::google::protobuf::Arena* arena, const WalletResponse& from)
    : WalletResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE WalletResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void WalletResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, new_balance_),
           0,
           offsetof(Impl_, success_) -
               offsetof(Impl_, new_balance_) +
               sizeof(Impl_::success_));
}
WalletResponse::~WalletResponse() {
  // @@protoc_insertion_point(destructor:user.WalletResponse)
  SharedDtor(*this);
}
inline void WalletResponse::SharedDtor(MessageLite& self) {
  WalletResponse& this_ = static_cast<WalletResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* WalletResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) WalletResponse(arena);
}
constexpr auto WalletResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(WalletResponse),
                                            alignof(WalletResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull WalletResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_WalletResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &WalletResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<WalletResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &WalletResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<WalletResponse>(), &WalletResponse::ByteSizeLong,
            &WalletResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(WalletResponse, _impl_._cached_size_),
        false,
    },
    &WalletResponse::kDescriptorMethods,
    &descriptor_table_user_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* WalletResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2> WalletResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::user::WalletResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // double used_margin = 4;
    {::_pbi::TcParser::FastF64S1,
     {33, 63, 0, PROTOBUF_FIELD_OFFSET(WalletResponse, _impl_.used_margin_)}},
    // double new_balance = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 63, 0, PROTOBUF_FIELD_OFFSET(WalletResponse, _impl_.new_balance_)}},
    // bool success = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(WalletResponse, _impl_.success_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(WalletResponse, _impl_.success_)}},
    // double available_balance = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 63, 0, PROTOBUF_FIELD_OFFSET(WalletResponse, _impl_.available_balance_)}},
  }}, {{
    65535, 65535
  }}, {{
    // double new_balance = 1;
    {PROTOBUF_FIELD_OFFSET(WalletResponse, _impl_.new_balance_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // bool success = 2;
    {PROTOBUF_FIELD_OFFSET(WalletResponse, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // double available_balance = 3;
    {PROTOBUF_FIELD_OFFSET(WalletResponse, _impl_.available_balance_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double used_margin = 4;
    {PROTOBUF_FIELD_OFFSET(WalletResponse, _impl_.used_margin_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void WalletResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:user.WalletResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.new_balance_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.success_) -
      reinterpret_cast<char*>(&_impl_.new_balance_)) + sizeof(_impl_.success_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* WalletResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const WalletResponse& this_ = static_cast<const WalletResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* WalletResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const WalletResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:user.WalletResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // double new_balance = 1;
          if (::absl::bit_cast<::uint64_t>(this_._internal_new_balance()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                1, this_._internal_new_balance(), target);
          }

          // bool success = 2;
          if (this_._internal_success() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_success(), target);
          }

          // double available_balance = 3;
          if (::absl::bit_cast<::uint64_t>(this_._internal_available_balance()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                3, this_._internal_available_balance(), target);
          }

          // double used_margin = 4;
          if (::absl::bit_cast<::uint64_t>(this_._internal_used_margin()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                4, this_._internal_used_margin(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:user.WalletResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t WalletResponse::ByteSizeLong(const MessageLite& base) {
          const WalletResponse& this_ = static_cast<const WalletResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t WalletResponse::ByteSizeLong() const {
          const WalletResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:user.WalletResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // double new_balance = 1;
            if (::absl::bit_cast<::uint64_t>(this_._internal_new_balance()) != 0) {
              total_size += 9;
            }
            // double available_balance = 3;
            if (::absl::bit_cast<::uint64_t>(this_._internal_available_balance()) != 0) {
              total_size += 9;
            }
            // double used_margin = 4;
            if (::absl::bit_cast<::uint64_t>(this_._internal_used_margin()) != 0) {
              total_size += 9;
            }
            // bool success = 2;
            if (this_._internal_success() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void WalletResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<WalletResponse*>(&to_msg);
  auto& from = static_cast<const WalletResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:user.WalletResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint64_t>(from._internal_new_balance()) != 0) {
    _this->_impl_.new_balance_ = from._impl_.new_balance_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_available_balance()) != 0) {
    _this->_impl_.available_balance_ = from._impl_.available_balance_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_used_margin()) != 0) {
    _this->_impl_.used_margin_ = from._impl_.used_margin_;
  }
  if (from._internal_success() != 0) {
    _this->_impl_.success_ = from._impl_.success_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void WalletResponse::CopyFrom(const WalletResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:user.WalletResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void WalletResponse::InternalSwap(WalletResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(WalletResponse, _impl_.success_)
      + sizeof(WalletResponse::_impl_.success_)
      - PROTOBUF_FIELD_OFFSET(WalletResponse, _impl_.new_balance_)>(
          reinterpret_cast<char*>(&_impl_.new_balance_),
          reinterpret_cast<char*>(&other->_impl_.new_balance_));
}

::google::protobuf::Metadata WalletResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UserIdRequest::_Internal {
 public:
};

UserIdRequest::UserIdRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:user.UserIdRequest)
}
inline PROTOBUF_NDEBUG_INLINE UserIdRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::user::UserIdRequest& from_msg)
      : user_id_(arena, from.user_id_),
        _cached_size_{0} {}

UserIdRequest::UserIdRequest(
    ::google::protobuf::Arena* arena,
    const UserIdRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UserIdRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:user.UserIdRequest)
}
inline PROTOBUF_NDEBUG_INLINE UserIdRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : user_id_(arena),
        _cached_size_{0} {}

inline void UserIdRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
UserIdRequest::~UserIdRequest() {
  // @@protoc_insertion_point(destructor:user.UserIdRequest)
  SharedDtor(*this);
}
inline void UserIdRequest::SharedDtor(MessageLite& self) {
  UserIdRequest& this_ = static_cast<UserIdRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.user_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* UserIdRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) UserIdRequest(arena);
}
constexpr auto UserIdRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(UserIdRequest),
                                            alignof(UserIdRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull UserIdRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_UserIdRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &UserIdRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<UserIdRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &UserIdRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<UserIdRequest>(), &UserIdRequest::ByteSizeLong,
            &UserIdRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(UserIdRequest, _impl_._cached_size_),
        false,
    },
    &UserIdRequest::kDescriptorMethods,
    &descriptor_table_user_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* UserIdRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 34, 2> UserIdRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::user::UserIdRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string user_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(UserIdRequest, _impl_.user_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string user_id = 1;
    {PROTOBUF_FIELD_OFFSET(UserIdRequest, _impl_.user_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\7\0\0\0\0\0\0"
    "user.UserIdRequest"
    "user_id"
  }},
};

PROTOBUF_NOINLINE void UserIdRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:user.UserIdRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.user_id_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* UserIdRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const UserIdRequest& this_ = static_cast<const UserIdRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* UserIdRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const UserIdRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:user.UserIdRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string user_id = 1;
          if (!this_._internal_user_id().empty()) {
            const std::string& _s = this_._internal_user_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "user.UserIdRequest.user_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:user.UserIdRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t UserIdRequest::ByteSizeLong(const MessageLite& base) {
          const UserIdRequest& this_ = static_cast<const UserIdRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t UserIdRequest::ByteSizeLong() const {
          const UserIdRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:user.UserIdRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string user_id = 1;
            if (!this_._internal_user_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_user_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void UserIdRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UserIdRequest*>(&to_msg);
  auto& from = static_cast<const UserIdRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:user.UserIdRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_user_id().empty()) {
    _this->_internal_set_user_id(from._internal_user_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UserIdRequest::CopyFrom(const UserIdRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:user.UserIdRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UserIdRequest::InternalSwap(UserIdRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.user_id_, &other->_impl_.user_id_, arena);
}

::google::protobuf::Metadata UserIdRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UserMetadataResponse::_Internal {
 public:
};

UserMetadataResponse::UserMetadataResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:user.UserMetadataResponse)
}
inline PROTOBUF_NDEBUG_INLINE UserMetadataResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::user::UserMetadataResponse& from_msg)
      : user_id_(arena, from.user_id_),
        role_(arena, from.role_),
        _cached_size_{0} {}

UserMetadataResponse::UserMetadataResponse(
    ::google::protobuf::Arena* arena,
    const UserMetadataResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UserMetadataResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.kyc_verified_ = from._impl_.kyc_verified_;

  // @@protoc_insertion_point(copy_constructor:user.UserMetadataResponse)
}
inline PROTOBUF_NDEBUG_INLINE UserMetadataResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : user_id_(arena),
        role_(arena),
        _cached_size_{0} {}

inline void UserMetadataResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.kyc_verified_ = {};
}
UserMetadataResponse::~UserMetadataResponse() {
  // @@protoc_insertion_point(destructor:user.UserMetadataResponse)
  SharedDtor(*this);
}
inline void UserMetadataResponse::SharedDtor(MessageLite& self) {
  UserMetadataResponse& this_ = static_cast<UserMetadataResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.user_id_.Destroy();
  this_._impl_.role_.Destroy();
  this_._impl_.~Impl_();
}

inline void* UserMetadataResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) UserMetadataResponse(arena);
}
constexpr auto UserMetadataResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(UserMetadataResponse),
                                            alignof(UserMetadataResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull UserMetadataResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_UserMetadataResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &UserMetadataResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<UserMetadataResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &UserMetadataResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<UserMetadataResponse>(), &UserMetadataResponse::ByteSizeLong,
            &UserMetadataResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(UserMetadataResponse, _impl_._cached_size_),
        false,
    },
    &UserMetadataResponse::kDescriptorMethods,
    &descriptor_table_user_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* UserMetadataResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 45, 2> UserMetadataResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::user::UserMetadataResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string user_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(UserMetadataResponse, _impl_.user_id_)}},
    // string role = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(UserMetadataResponse, _impl_.role_)}},
    // bool kyc_verified = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(UserMetadataResponse, _impl_.kyc_verified_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(UserMetadataResponse, _impl_.kyc_verified_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string user_id = 1;
    {PROTOBUF_FIELD_OFFSET(UserMetadataResponse, _impl_.user_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string role = 2;
    {PROTOBUF_FIELD_OFFSET(UserMetadataResponse, _impl_.role_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool kyc_verified = 3;
    {PROTOBUF_FIELD_OFFSET(UserMetadataResponse, _impl_.kyc_verified_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\31\7\4\0\0\0\0\0"
    "user.UserMetadataResponse"
    "user_id"
    "role"
  }},
};

PROTOBUF_NOINLINE void UserMetadataResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:user.UserMetadataResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.user_id_.ClearToEmpty();
  _impl_.role_.ClearToEmpty();
  _impl_.kyc_verified_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* UserMetadataResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const UserMetadataResponse& this_ = static_cast<const UserMetadataResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* UserMetadataResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const UserMetadataResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:user.UserMetadataResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string user_id = 1;
          if (!this_._internal_user_id().empty()) {
            const std::string& _s = this_._internal_user_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "user.UserMetadataResponse.user_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string role = 2;
          if (!this_._internal_role().empty()) {
            const std::string& _s = this_._internal_role();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "user.UserMetadataResponse.role");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // bool kyc_verified = 3;
          if (this_._internal_kyc_verified() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                3, this_._internal_kyc_verified(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:user.UserMetadataResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t UserMetadataResponse::ByteSizeLong(const MessageLite& base) {
          const UserMetadataResponse& this_ = static_cast<const UserMetadataResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t UserMetadataResponse::ByteSizeLong() const {
          const UserMetadataResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:user.UserMetadataResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string user_id = 1;
            if (!this_._internal_user_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_user_id());
            }
            // string role = 2;
            if (!this_._internal_role().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_role());
            }
            // bool kyc_verified = 3;
            if (this_._internal_kyc_verified() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void UserMetadataResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UserMetadataResponse*>(&to_msg);
  auto& from = static_cast<const UserMetadataResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:user.UserMetadataResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_user_id().empty()) {
    _this->_internal_set_user_id(from._internal_user_id());
  }
  if (!from._internal_role().empty()) {
    _this->_internal_set_role(from._internal_role());
  }
  if (from._internal_kyc_verified() != 0) {
    _this->_impl_.kyc_verified_ = from._impl_.kyc_verified_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UserMetadataResponse::CopyFrom(const UserMetadataResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:user.UserMetadataResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UserMetadataResponse::InternalSwap(UserMetadataResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.user_id_, &other->_impl_.user_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.role_, &other->_impl_.role_, arena);
        swap(_impl_.kyc_verified_, other->_impl_.kyc_verified_);
}

::google::protobuf::Metadata UserMetadataResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace user
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_user_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
