// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: symbol.proto
#ifndef GRPC_symbol_2eproto__INCLUDED
#define GRPC_symbol_2eproto__INCLUDED

#include "symbol.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace symbol {

class SymbolService final {
 public:
  static constexpr char const* service_full_name() {
    return "symbol.SymbolService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetSymbolInfo(::grpc::ClientContext* context, const ::symbol::SymbolRequest& request, ::symbol::SymbolResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::symbol::SymbolResponse>> AsyncGetSymbolInfo(::grpc::ClientContext* context, const ::symbol::SymbolRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::symbol::SymbolResponse>>(AsyncGetSymbolInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::symbol::SymbolResponse>> PrepareAsyncGetSymbolInfo(::grpc::ClientContext* context, const ::symbol::SymbolRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::symbol::SymbolResponse>>(PrepareAsyncGetSymbolInfoRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetSymbolInfo(::grpc::ClientContext* context, const ::symbol::SymbolRequest* request, ::symbol::SymbolResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetSymbolInfo(::grpc::ClientContext* context, const ::symbol::SymbolRequest* request, ::symbol::SymbolResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::symbol::SymbolResponse>* AsyncGetSymbolInfoRaw(::grpc::ClientContext* context, const ::symbol::SymbolRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::symbol::SymbolResponse>* PrepareAsyncGetSymbolInfoRaw(::grpc::ClientContext* context, const ::symbol::SymbolRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetSymbolInfo(::grpc::ClientContext* context, const ::symbol::SymbolRequest& request, ::symbol::SymbolResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::symbol::SymbolResponse>> AsyncGetSymbolInfo(::grpc::ClientContext* context, const ::symbol::SymbolRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::symbol::SymbolResponse>>(AsyncGetSymbolInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::symbol::SymbolResponse>> PrepareAsyncGetSymbolInfo(::grpc::ClientContext* context, const ::symbol::SymbolRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::symbol::SymbolResponse>>(PrepareAsyncGetSymbolInfoRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetSymbolInfo(::grpc::ClientContext* context, const ::symbol::SymbolRequest* request, ::symbol::SymbolResponse* response, std::function<void(::grpc::Status)>) override;
      void GetSymbolInfo(::grpc::ClientContext* context, const ::symbol::SymbolRequest* request, ::symbol::SymbolResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::symbol::SymbolResponse>* AsyncGetSymbolInfoRaw(::grpc::ClientContext* context, const ::symbol::SymbolRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::symbol::SymbolResponse>* PrepareAsyncGetSymbolInfoRaw(::grpc::ClientContext* context, const ::symbol::SymbolRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetSymbolInfo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetSymbolInfo(::grpc::ServerContext* context, const ::symbol::SymbolRequest* request, ::symbol::SymbolResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetSymbolInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetSymbolInfo() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetSymbolInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSymbolInfo(::grpc::ServerContext* /*context*/, const ::symbol::SymbolRequest* /*request*/, ::symbol::SymbolResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetSymbolInfo(::grpc::ServerContext* context, ::symbol::SymbolRequest* request, ::grpc::ServerAsyncResponseWriter< ::symbol::SymbolResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetSymbolInfo<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetSymbolInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetSymbolInfo() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::symbol::SymbolRequest, ::symbol::SymbolResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::symbol::SymbolRequest* request, ::symbol::SymbolResponse* response) { return this->GetSymbolInfo(context, request, response); }));}
    void SetMessageAllocatorFor_GetSymbolInfo(
        ::grpc::MessageAllocator< ::symbol::SymbolRequest, ::symbol::SymbolResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::symbol::SymbolRequest, ::symbol::SymbolResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetSymbolInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSymbolInfo(::grpc::ServerContext* /*context*/, const ::symbol::SymbolRequest* /*request*/, ::symbol::SymbolResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetSymbolInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::symbol::SymbolRequest* /*request*/, ::symbol::SymbolResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetSymbolInfo<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetSymbolInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetSymbolInfo() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetSymbolInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSymbolInfo(::grpc::ServerContext* /*context*/, const ::symbol::SymbolRequest* /*request*/, ::symbol::SymbolResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetSymbolInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetSymbolInfo() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetSymbolInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSymbolInfo(::grpc::ServerContext* /*context*/, const ::symbol::SymbolRequest* /*request*/, ::symbol::SymbolResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetSymbolInfo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetSymbolInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetSymbolInfo() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetSymbolInfo(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetSymbolInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSymbolInfo(::grpc::ServerContext* /*context*/, const ::symbol::SymbolRequest* /*request*/, ::symbol::SymbolResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetSymbolInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetSymbolInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetSymbolInfo() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::symbol::SymbolRequest, ::symbol::SymbolResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::symbol::SymbolRequest, ::symbol::SymbolResponse>* streamer) {
                       return this->StreamedGetSymbolInfo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetSymbolInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetSymbolInfo(::grpc::ServerContext* /*context*/, const ::symbol::SymbolRequest* /*request*/, ::symbol::SymbolResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetSymbolInfo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::symbol::SymbolRequest,::symbol::SymbolResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetSymbolInfo<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetSymbolInfo<Service > StreamedService;
};

}  // namespace symbol


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_symbol_2eproto__INCLUDED
